### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by ghost** [coleblvck/MethodCall#6]
Personally, I've never needed to turn on my phones torch or launch an app remotly. So that makes me geniuenlly curious as to ***why*** this app was made, and with the trigger being phone calls from diffrent numbers. I doubt it would be to locate your phone since [FMD](https://f-droid.org/packages/de.nulide.findmydevice/) does that just fine? Do people call you when they cant reach you on another chatting platform so you have it open quickly when they holler to see whats going on? Are there sim providers who dont provide sms? I'm at a loss.

**Comment by coleblvck** [comment]
The application is exactly as described: an android automation application. I just have not gotten around to adding the other actions on my list as I have been relatively busy. If you look into the architecture of this application, you'd see that it was not built around toggling flashlights or launching apps but automation at its core. You (or anyone) could easily take a fork and add a new action in a few lines of code, all it would take is understanding how to do so. I had this application sitting in my repo for months as I was busy and I decided "let me just show what it could do" and then put it out, as time goes on, I would just add actions from my list.

This app is easily (arguably) the most useful app on my github at the moment. So to answer your question, it is not just some useless find-my-device app or anything close to that. I try not to make pointless apps.
